[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff]
select = [
    "D", # pydocstyle
    "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "W", # pycodestyle warnings
]
ignore = []
line-length = 120

extend-ignore = [
    "D105", # undocumented-magic-method
    "D107", # undocumented-public-init
    "D205", # blank-line-after-summary
    "D415" # ends-in-punctuation
]

[tool.ruff.lint.pydocstyle]
# docstringはgoogle style
convention = "google"

[tool.ruff.per-file-ignores]
"__init__.py" = ["D104"] # ignore no docstrings in __init__.py
